ALTER SESSION
SET NLS_TERRITORY = 'AMERICA';

ALTER SESSION
SET NLS_LANGUAGE = 'AMERICAN';

SET LINESIZE 500
SET PAGESIZE 30
SET SERVEROUTPUT ON
define _editor = "C:\Program Files (x86)\Notepad++\notepad++.exe"