ALTER SESSION
SET NLS_TERRITORY = 'AMERICA';

ALTER SESSION
SET NLS_LANGUAGE = 'AMERICAN';

SET LINESIZE 500
SET PAGESIZE 30
SET AUTOPRINT ON
set serveroutput on

DEFINE _EDITOR = 'C:\Program Files\Notepad++\notepad++.exe'